export * from './cliente.repository.interface'
export * from './ordem-servico.repository.interface'
export * from './peca.repository.interface'
export * from './servico.repository.interface'
export * from './veiculo.repository.interface'
